### ISSUE TITLE
Science Memory benchmark methods

### ISSUE THREAD

**Issue by Zig-Rust-Odin** [PrintN/Human-Benchmark#1]
If we could make a Memory benchmark test of these mnemonics that would be very useful.
https://artofmemory.com/
https://memoryleague.com/
[Forgetting Curve](https://en.wikipedia.org/wiki/Forgetting_curve) Scientific Memory Review Time.

---
I prefer word games that answer multiple choice logical reasoning questions. Word games, they help me improve my memory and logical reasoning skills.

**Comment by PrintN** [comment]
That sounds interesting! Maybe we could make a test where users read an article on a science-related topic and then answer questions based on what they remember?
