### ISSUE TITLE
Intelligence Quotient question with no correct answer

### ISSUE THREAD

**Issue by Macemacerson** [PrintN/Human-Benchmark#12]
![Screenshot_20241209-212427](https://github.com/user-attachments/assets/3fc34a0f-72cc-4dc0-880e-a005ecd609b1)

The formula is each line gets an additional block with each iteration. The correct answer is therefore 3 blocks on top, 4 in the middle and 5 at the bottom.

Are these questions actually proofread before being implemented in the app or am I going insane and the answer is one of the provided options?

**Comment by PrintN** [comment]
Hi there! Most of these questions were taken from another open-source repository. I'm currently working on replacing them with better questions. Regarding question 14, you're correct, the answer isn't listed there.
