### ISSUE TITLE
Chimp test with more than 14 tiles

### ISSUE THREAD

**Issue by liviu-vasut** [PrintN/Human-Benchmark#13]
Somehow I managed to reach to level 15, I've clicked all tiles in order, and when I clicked the last one, the 15th, the app froze. The tile remained hidden and the back button was unresponsive as well. Understandably, I did not try again :)

**Comment by PrintN** [comment]
Hi, thanks for submitting this issue. I will look further into this.

**Comment by jnsh** [comment]
Same thing happens to me every time I hit the last tile on level 11. Just a guess, but maybe the app crashes if there is not enough screen estate for every tile..

**Comment by liviu-vasut** [comment]
Today I successfully reached level 16 (where my head blew up and I stopped), so it's not related to 15.

@jnsh you might be on to something, the logic accounts for the screen size, naturally, but then it loops to find a free spot. At some point it will not find a free spot and just loop forever. This will happen sooner on small screens and also at random depending on the generated tile distribution.

https://github.com/PrintN/Human-Benchmark/blob/main/lib/chimp.dart#L85

@PrintN , one solution would be to add a safeguard to only allow a fixed number of searches and if that point is reached to gradually reduce the boxSize variable until you finally find a spot. The size of the tile displayed for the user can also decrease to avoid covering the numbers. This way you can do level ups indefinitely or at least accommodate even the biggest brainiacs :).

**Comment by PrintN** [comment]
This issue has now been fixed. Please update the app from the release section 😀

**Comment by liviu-vasut** [comment]
thanks @PrintN for looking into this. For what it's worth, I think it can still fail on small screens, but I guess we'll see, maybe there aren't that many users with phones like that :).

I installed the app from F-Droid, so I'll wait for the update there.
Thanks again.
