### ISSUE TITLE
Android TV playable but 3 tests cannot

### ISSUE THREAD

**Issue by TruongTanLuc201270** [PrintN/Human-Benchmark#15]
![Screenshot_20241215-114219](https://github.com/user-attachments/assets/7f2e089e-2618-4202-bf28-5de9a3d7ea06)
![Screenshot_20241215-114207](https://github.com/user-attachments/assets/c65ddd3e-280c-4cdc-bcbc-26cb39b760d9)
![Screenshot_20241215-114149](https://github.com/user-attachments/assets/83f20d99-dfab-4f41-89e4-e869631dc2d5)

**Comment by PrintN** [comment]
Hi, thanks for submitting this issue. The app is currently meant to only be played on mobile screens. I will look further into making the app responsive for different screens.

**Comment by TruongTanLuc201270** [comment]
Failed, only potrait screen to be work, landscape no supported because not suitable for TV and tablets.
