### ISSUE TITLE
Rotate and flip the "World" plot in the statistics and overlay the user history using the horizontal axis for time

### ISSUE THREAD

**Issue by TiagoTiago** [PrintN/Human-Benchmark#16]
With the "World" plot rotated 90 degrees and flipped vertically so that the vertical axis represents score ("better" towards the top and "worse" towards the bottom) and the horizontal axis the distribution of the population; you can have the vertical axis of the User's plot also matching score, and the horizontal can be used as time, so the user can see how their skills changed over time while simultaneously seeing where they stand compared the the distribution of the general population. This of course would imply two sets of labels for the axes; if you feel the "percentage of the population" isn't obviously implicit; in that's the case, you have a second line of labels, and color each scale according to respective plot.

And ideally, the time axis should be zoomable and scrollable, so people that use the app for a long time can get a closer look at particular moments and skip long gaps if they want.

Might also be interesting to have an option of displaying the user score with something like a weight/exponential average, weighting closer values more strongly, to produce a smoother line if desirable and make potential games between exercise periods less glaring.

Additionally, there should be an option to erase history, as well as individual entries.

**Comment by PrintN** [comment]
Thank you for your suggestions! I will experiment with different ways of displaying the statistics.
**Please note** that the app is 100% offline, so the entire history isn't saved to conserve space. There is also already an option to delete all your history.

**Comment by TiagoTiago** [comment]
Would be nice to save the history to better keep track of progress over time. For me, local-only without online backup would be perfectly fine; specially with the exporting option from my other suggestion to allow for manual backups.
