### ISSUE TITLE
[BUG] Dual N-Back doesn't seem to do anything

### ISSUE THREAD

**Issue by TiagoTiago** [PrintN/Human-Benchmark#18]
Starting the test, it displays the 3x3 grid with one square lit up, the "N-Back" text and scores above, and the 3 buttons bellow; but nothing seems to happen no matter where I tap or drag on the screen, the only thing I can do is hit the back arrow up top and leave it.

Not sure what more info I can provide to help; lemme know if you can think of anything that would be useful that I provide. Edit: Oh, and I'm using the latest version from F-Droid at the moment, 1.0.6

**Comment by schneidr** [comment]
I'm having exactly the same problem. Audio is on (hearing test works), all buttons disabled.

Pixel Tablet with GrapheneOS 15, app version is 1.0.8 from F-Droid.

[Human Benchmark log 65a18959e3bf.txt](https://github.com/user-attachments/files/19142839/Human.Benchmark.log.65a18959e3bf.txt)
