### ISSUE TITLE
Architecture specific apk to reduce apk size 

### ISSUE THREAD

**Issue by HusniMuhammad** [PrintN/Human-Benchmark#2]
Architecture specific apk to reduce apk size

**Comment by PrintN** [comment]
Thank you for the suggestion. However, I won't be implementing architecture-specific APKs mainly because F-Droid prefers universal APKs to ensure compatibility across all devices.

**Comment by HusniMuhammad** [comment]
> Thank you for the suggestion. However, I won't be implementing architecture-specific APKs mainly because F-Droid prefers universal APKs to ensure compatibility across all devices.

For GitHub releases?

**Comment by PrintN** [comment]
Good point. I will include architecture-specific APKs in the next GitHub release 😀
