### ISSUE TITLE
IQ test Previous and Next buttons should not move

### ISSUE THREAD

**Issue by hackerb9** [PrintN/Human-Benchmark#26]
![Screenshot_20241216-153929](https://github.com/user-attachments/assets/a7f17d7f-1613-443c-b14f-39c775e0e20c)

Standardized IQ tests typically allow one to skip problems and come back later if there is extra time at the end. To facilitate that, the Previous and Next buttons should be at a fixed location on the screen so one can rapidly tap in the same location to move backwards and forwards. 

However, as question 21 demonstrates, sometimes the buttons are higher or lower depending on the size of the possible answers. If one is tapping rapidly they will accidentally select a different answer and will have to take time to fix it, if they even notice.

A simple solution would be to always pin the buttons to the bottom of the screen.

**Comment by PrintN** [comment]
This should be an easy fix.
