### ISSUE TITLE
IQ test quits too quickly and then doesn't let the user back in

### ISSUE THREAD

**Issue by hackerb9** [PrintN/Human-Benchmark#27]
![Screenshot_20241216-155000](https://github.com/user-attachments/assets/87d132cd-0e44-4896-a88c-0c16a42598d5)

The final question exits the IQ test as soon as the user taps their first choice. This is a problem as it prevents people from using their extra time to review and make better choices.

In a related bug, if the user skipped any questions by hitting Next, when they get to the 30th question the Next button will appear to be broken as it does nothing with no indication as to why 

Fix: The final question should have a Next button which takes the user to a screen that says, "You still have 5m36s remaining to go back and review your answers. If wish to quit early click on Finish."

Importantly, the "Finish" button must not be located in the same place as the "Next" button so that people will not hit it by accident when zooming quickly forward as they make sure they answered all the questions.

**Comment by PrintN** [comment]
Than you for submitting this issue. I will add a "Finish" button at the 30th question.
