### ISSUE TITLE
number memory bug

### ISSUE THREAD

**Issue by zmn28hgbn59kcmlpio8unfh7fdre523esd28q9a** [PrintN/Human-Benchmark#8]
when starting number memory task, it instantly shows the input field asking what was the number, but it didnt show any number in first place.

e.g. on human benchmark site it would show the number for couple seconds, and as you progress further the delay before number disappear is increased.

however on this android app it doesnt even show the number not even for 100ms, makes it impossible to pass first digit test.

**Comment by PrintN** [comment]
Hi,
Thank you for submitting the issue. I’m unable to reproduce the bug you described. In the Number Memory task, pressing the "Start Test" button should display a one-digit number for about two seconds, with the time increasing as more digits are added.

Could you please let me know which version of the Human Benchmark app you are using? Additionally, if possible, could you provide a screen recording of the issue?

**Comment by zmn28hgbn59kcmlpio8unfh7fdre523esd28q9a** [comment]
tested with f-droid 1.0.3 and latest github build 1.0.4

apparently paying close attention it seems like the delay is less than 100ms.


https://github.com/user-attachments/assets/6ea7854e-4381-4fbf-bea3-a9ca77887536

**Comment by PrintN** [comment]
Thank you for providing a video. I will look further into this bug 😀

**Comment by GiorgosXou** [comment]
I'm experiencing the same issue. The problem  is subject to the 'transition animation scale" time *(some people, or phones,  turn off those animations for improved performance)* resulting in this exact issue. 

![Screenshot_2024-12-01-18-54-26-186_com android settings](https://github.com/user-attachments/assets/8dd141a0-d43e-4ccc-bb1d-a2158e3215b2)

**Comment by GiorgosXou** [comment]
@zmn28hgbn59kcmlpio8unfh7fdre523esd28q9a The test shouldn't depend on this time. This issue needs to be addressed via the app. Additionally, I wouldn't recommend you to change those value, as it effects the performance of your phone.
